# Generated by Django 4.2.7 on 2025-09-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmetric',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.campaign'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.region'),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='marketing_app.customer'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='manufacturing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.manufacturing'),
        ),
        migrations.AlterField(
            model_name='dispatchchecklist',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.dispatch'),
        ),
        migrations.AlterField(
            model_name='gadrawing',
            name='urs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.urs'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_app.campaign'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.lead'),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.workorder'),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.quotation'),
        ),
        migrations.AlterField(
            model_name='packingdetails',
            name='manufacturing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.manufacturing'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.workorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.customer'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_app.quotation'),
        ),
        migrations.AlterField(
            model_name='qctracking',
            name='manufacturing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.manufacturing'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.customer'),
        ),
        migrations.AlterField(
            model_name='technicaldiscussion',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.quotation'),
        ),
        migrations.AlterField(
            model_name='urs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.customer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.customer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_app.customerlocation'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.purchaseorder'),
        ),
    ]
