# Generated by Django 4.2.7 on 2025-09-04 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0002_alter_campaignmetric_campaign_alter_customer_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
                ('revision_reason', models.CharField(choices=[('price_adjustment', 'Price Adjustment'), ('specification_change', 'Specification Change'), ('terms_modification', 'Terms Modification'), ('customer_request', 'Customer Request'), ('market_conditions', 'Market Conditions'), ('competitor_response', 'Competitor Response'), ('other', 'Other')], max_length=30)),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changes_summary', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('negotiation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_revisions', to='marketing_app.negotiation')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='marketing_app.quotation')),
            ],
            options={
                'ordering': ['-revision_date'],
            },
        ),
    ]
