# Generated by Django 4.2.7 on 2025-09-04 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0003_quotationrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VisitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Executive'), ('secondary', 'Secondary Executive'), ('technical', 'Technical Expert'), ('manager', 'Manager'), ('observer', 'Observer')], default='secondary', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text="Specific notes about this participant's role in the visit")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='marketing_app.visit')),
            ],
            options={
                'ordering': ['-is_primary', 'role', 'user__first_name'],
                'unique_together': {('visit', 'user')},
            },
        ),
    ]
