# Generated by Django 4.2.7 on 2025-09-04 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0004_alter_visit_assigned_to_visitparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('advance', 'Advance Payment'), ('credit', 'Credit Payment'), ('l_c', 'Letter of Credit'), ('bank_guarantee', 'Bank Guarantee'), ('cheque', 'Cheque'), ('neft_rtgs', 'NEFT/RTGS'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms_declared',
            field=models.TextField(blank=True, help_text='Detailed payment terms as declared by customer'),
        ),
        migrations.CreateModel(
            name='PaymentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('advance', 'Advance Payment'), ('credit', 'Credit Payment'), ('l_c', 'Letter of Credit'), ('bank_guarantee', 'Bank Guarantee'), ('cheque', 'Cheque'), ('neft_rtgs', 'NEFT/RTGS'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('payment_terms_declared', models.TextField(help_text='Payment terms as declared by customer')),
                ('follow_up_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_followups', to='marketing_app.purchaseorder')),
            ],
            options={
                'ordering': ['-follow_up_date', '-created_at'],
            },
        ),
    ]
