# Generated by Django 4.2.7 on 2025-09-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0006_annualexhibitionbudget_budgetcategory_budgetapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryLog',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Month of enquiry', max_length=20)),
                ('enquiry_number', models.CharField(help_text='ENQ-No', max_length=50, unique=True)),
                ('enquiry_date', models.DateField(help_text='Enquiry Date')),
                ('location', models.CharField(help_text='Location', max_length=200)),
                ('enquiry_mail', models.EmailField(help_text='Enquiry Mail', max_length=254)),
                ('quote_number', models.CharField(blank=True, help_text='Quote No.', max_length=50)),
                ('quote_date', models.DateField(blank=True, help_text='Quote Date', null=True)),
                ('offer_category', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom'), ('bulk', 'Bulk Order'), ('trial', 'Trial')], default='standard', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('requirement_details', models.TextField()),
                ('quote_send', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('follow_up', models.TextField(blank=True, help_text='Follow up notes and status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry Log',
                'verbose_name_plural': 'Inquiry Logs',
                'ordering': ['-enquiry_date', '-created_at'],
            },
        ),
    ]
