# Generated by Django 4.2.7 on 2025-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0007_inquirylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirylog',
            name='enquiry_through',
            field=models.CharField(choices=[('regional_head', 'Regional Head'), ('area_sales_manager', 'Area Sales Manager'), ('enquiry_mail', 'Enquiry Mail'), ('website', 'Website'), ('individual_vp', 'Individual (VP)'), ('individual_india_head', 'Individual (India Head)'), ('individual_other', 'Individual (Other)'), ('exhibition', 'Exhibition'), ('mail', 'Mail'), ('call', 'Call')], default='enquiry_mail', help_text='How the enquiry was received', max_length=30),
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='follow_up_status',
            field=models.CharField(choices=[('yes_updated', 'Yes (Updated in Follow-Up Status)'), ('yet_not', 'Yet Not (Not updated in Follow-Up Status)')], default='yet_not', help_text='Follow-up status', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquirylog',
            name='offer_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('customized', 'Customized'), ('discounted', 'Discounted'), ('final', 'Final')], default='standard', max_length=20),
        ),
    ]
