# Generated by Django 4.2.7 on 2025-09-05 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0010_purchaseordermis_projecttoday_orderexpectednextmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISPurchaseOrder',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=100)),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact_person_details', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('enquiry_log_number', models.CharField(blank=True, max_length=50)),
                ('quote_no', models.CharField(blank=True, max_length=50)),
                ('work_order_number', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('machine_details', models.TextField(blank=True)),
                ('equipment_sr_number', models.CharField(blank=True, max_length=100)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ap_quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage_order', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MIS Purchase Order',
                'verbose_name_plural': 'MIS Purchase Orders',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='followupstatus',
            options={'ordering': ['-follow_up_date', '-created_at'], 'verbose_name': 'Follow-Up Status', 'verbose_name_plural': 'Follow-Up Status'},
        ),
        migrations.RenameField(
            model_name='odplan',
            old_name='sr_no',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='newdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderexpectednextmonth',
            name='ap_quote_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderexpectednextmonth',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderexpectednextmonth',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderMIS',
        ),
    ]
