# Generated by Django 4.2.7 on 2025-09-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0011_mispurchaseorder_alter_followupstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODPlanVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month of planning', max_length=20)),
                ('region', models.CharField(help_text='Region for visit', max_length=100)),
                ('date', models.DateField(help_text='Planned date for visit')),
                ('name', models.CharField(help_text='Person name', max_length=100)),
                ('visit_plan', models.CharField(help_text='Visit plan details', max_length=200)),
                ('location', models.CharField(help_text='Visit location', max_length=200)),
                ('company_name', models.CharField(help_text='Company to visit', max_length=200)),
                ('contact_person', models.CharField(help_text='Contact person name', max_length=100)),
                ('contact_no', models.CharField(help_text='Contact number', max_length=20)),
                ('mail_id', models.EmailField(help_text='Email address', max_length=254)),
                ('reason_for_visit', models.CharField(choices=[('first_visit', 'First Visit'), ('inquiry_collection', 'Inquiry Collection'), ('follow_up', 'Follow up'), ('casual_visit', 'Casual Visit'), ('order_finalization', 'Order Finalization'), ('technical_discussions', 'Technical Discussions'), ('payment_follow_up', 'Payment Follow up'), ('payment_collection', 'Payment Collection'), ('issue_escalation', 'Any Issue/Escalation'), ('upgradation_requirement', 'Upgradation Requirement'), ('amc_requirement', 'AMC Requirement')], help_text='Reason for visit', max_length=50)),
                ('appointment_status', models.CharField(choices=[('appointment_confirmed', 'Appointment confirmed'), ('direct_visit', 'Direct Visit')], help_text='Appointment status', max_length=30)),
                ('visit_status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('no_show', 'No Show')], default='planned', help_text='Visit status', max_length=20)),
                ('visited_on_date', models.DateField(blank=True, help_text='Actual visit date', null=True)),
                ('meeting_output', models.TextField(blank=True, help_text='Meeting output and results')),
                ('next_action_needed', models.TextField(blank=True, help_text='Next action needed if any')),
                ('next_follow_up_visit', models.DateField(blank=True, help_text='Next follow up visit date', null=True)),
                ('mail_status_about_visit', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('replied', 'Replied')], default='not_sent', help_text='Mail status about visit', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Additional comments if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OD Plan Visit Report',
                'verbose_name_plural': 'OD Plan Visit Reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ODPlanRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(help_text='General remarks if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OD Plan Remark',
                'verbose_name_plural': 'OD Plan Remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
