# Generated by Django 4.2.7 on 2025-09-05 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0012_odplanvisitreport_odplanremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PODetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer Name', max_length=200)),
                ('po_no', models.CharField(help_text='Purchase Order Number', max_length=100)),
                ('po_date', models.DateField(help_text='Purchase Order Date')),
                ('wo_no', models.CharField(help_text='Work Order Number', max_length=100)),
                ('contact_name', models.CharField(help_text='Contact Person Name', max_length=100)),
                ('contact_details', models.TextField(help_text='Contact Details')),
                ('tel_mob_no', models.CharField(help_text='Telephone/Mobile Number', max_length=20)),
                ('email_id', models.EmailField(help_text='Email Address', max_length=254)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount Percentage', max_digits=5, null=True)),
                ('advance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Advance Percentage', max_digits=5, null=True)),
                ('against_pi_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Against PI Percentage', max_digits=5, null=True)),
                ('against_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Against FAT Percentage', max_digits=5, null=True)),
                ('after_delivery_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='After Delivery Percentage', max_digits=5, null=True)),
                ('after_installation_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='After Installation Percentage', max_digits=5, null=True)),
                ('packing_forwarding', models.CharField(choices=[('inclusive', 'Inclusive'), ('extra_as_actual', 'Extra As Actual')], help_text='Packing & Forwarding', max_length=20)),
                ('transportation', models.CharField(choices=[('inclusive', 'Inclusive'), ('extra_as_actual', 'Extra As Actual')], help_text='Transportation', max_length=20)),
                ('marketing_dept', models.CharField(default='Miss. Pooja Kolse', help_text='Marketing Department Contact', max_length=100)),
                ('accounts_dept', models.CharField(default='Mr. Jitendra Tajanpure', help_text='Accounts Department Contact', max_length=100)),
                ('additional_contact', models.CharField(default='Mr. Harshal Ghoge', help_text='Additional Contact', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Details',
                'verbose_name_plural': 'PO Details',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
    ]
