# Generated by Django 4.2.7 on 2025-09-05 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0013_podetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='POStatus',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Month', max_length=20)),
                ('region', models.CharField(help_text='Region', max_length=100)),
                ('company', models.CharField(help_text='Company Name', max_length=200)),
                ('order_is_for', models.CharField(choices=[('stability', 'Stability'), ('tt', 'TT'), ('validation', 'Validation'), ('other', 'Other')], help_text='Order is for (Stability / TT / ...)', max_length=50)),
                ('po_number', models.CharField(help_text='PO Number', max_length=100)),
                ('responsible_marketing_person', models.CharField(help_text='Responsible Marketing Person', max_length=100)),
                ('coordinator', models.CharField(help_text='Coordinator', max_length=100)),
                ('po_date', models.DateField(help_text='PO Date')),
                ('po_value_without_gst', models.DecimalField(decimal_places=2, help_text='PO Value (Without GST)', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, help_text='GST', max_digits=12)),
                ('po_acceptance_date', models.DateField(blank=True, help_text='PO Acceptance Date', null=True)),
                ('wo_date', models.DateField(blank=True, help_text='WO Date', null=True)),
                ('payr01_agreed_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-01 Agreed Percentage', max_digits=5, null=True)),
                ('payr01_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-01 Agreed Amount', max_digits=12, null=True)),
                ('payr01_received_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-01 Received Percentage', max_digits=5, null=True)),
                ('payr01_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-01 Received Amount', max_digits=12, null=True)),
                ('payr01_received_date', models.DateField(blank=True, help_text='PayR-01 Received Date', null=True)),
                ('payr02_agreed_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-02 Agreed Percentage', max_digits=5, null=True)),
                ('payr02_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-02 Agreed Amount', max_digits=12, null=True)),
                ('payr02_received_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-02 Received Percentage', max_digits=5, null=True)),
                ('payr02_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-02 Received Amount', max_digits=12, null=True)),
                ('payr02_received_date', models.DateField(blank=True, help_text='PayR-02 Received Date', null=True)),
                ('payr03_agreed_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-03 Agreed Percentage', max_digits=5, null=True)),
                ('payr03_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-03 Agreed Amount', max_digits=12, null=True)),
                ('payr03_received_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-03 Received Percentage', max_digits=5, null=True)),
                ('payr03_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-03 Received Amount', max_digits=12, null=True)),
                ('payr03_received_date', models.DateField(blank=True, help_text='PayR-03 Received Date', null=True)),
                ('payr04_agreed_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-04 Agreed Percentage', max_digits=5, null=True)),
                ('payr04_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-04 Agreed Amount', max_digits=12, null=True)),
                ('payr04_received_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-04 Received Percentage', max_digits=5, null=True)),
                ('payr04_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-04 Received Amount', max_digits=12, null=True)),
                ('payr04_received_date', models.DateField(blank=True, help_text='PayR-04 Received Date', null=True)),
                ('payr05_agreed_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-05 Agreed Percentage', max_digits=5, null=True)),
                ('payr05_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-05 Agreed Amount', max_digits=12, null=True)),
                ('payr05_received_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-05 Received Percentage', max_digits=5, null=True)),
                ('payr05_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='PayR-05 Received Amount', max_digits=12, null=True)),
                ('payr05_received_date', models.DateField(blank=True, help_text='PayR-05 Received Date', null=True)),
                ('total_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total Agreed Amount', max_digits=12, null=True)),
                ('total_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total Received Amount', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Status',
                'verbose_name_plural': 'PO Status',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
    ]
