# Generated by Django 4.2.7 on 2025-09-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0014_postatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('work_order_no', models.CharField(help_text='Work Order No.', max_length=100)),
                ('equipment_no', models.CharField(help_text='Equipment No.', max_length=100)),
                ('delivery_date', models.DateField(help_text='Delivery Date')),
                ('equipment_type', models.CharField(help_text='Equipment type', max_length=200)),
                ('capacity', models.CharField(help_text='Capacity (Ltr)', max_length=50)),
                ('model', models.CharField(help_text='Model', max_length=100)),
                ('inner_body_moc', models.CharField(help_text='Inner Body MOC', max_length=100)),
                ('outer_body_moc', models.CharField(help_text='Outer Body MOC', max_length=100)),
                ('inside_dimensions', models.CharField(help_text='Inside dimensions (W x D x H in MM)', max_length=100)),
                ('outer_size', models.CharField(help_text='Outer Size (W x D x H in MM)', max_length=100)),
                ('temp_range', models.CharField(help_text='Temp Range', max_length=100)),
                ('accuracy', models.CharField(help_text='Accuracy', max_length=100)),
                ('uniformity', models.CharField(help_text='Uniformity', max_length=100)),
                ('controller_system', models.CharField(choices=[('plc_ab', 'PLC "AB"'), ('plc_delta', 'PLC Delta'), ('digital_controller', 'Digital Controller System'), ('microprocessor_pid', 'Microprocessor based PID Controller')], help_text='Controller System', max_length=50)),
                ('hmi_system', models.CharField(choices=[('hmi_43_ab', '4.3" AB'), ('hmi_43_delta', '4.3" Delta'), ('hmi_7_ab', '7" AB'), ('hmi_7_delta', '7" Delta'), ('other_na', 'Any Other/NA')], help_text='HMI System', max_length=50)),
                ('gsm_system', models.BooleanField(default=False, help_text='GSM System')),
                ('scanner', models.CharField(blank=True, help_text='Scanner', max_length=200)),
                ('software', models.CharField(blank=True, help_text='Software', max_length=200)),
                ('door_access_system', models.CharField(choices=[('password', 'Password Protected Door Access System'), ('biometric', 'Biometric Door Access System'), ('na', 'NA')], help_text='Door Access System', max_length=50)),
                ('hooter_system', models.CharField(choices=[('4_chamber', 'Yes (4 Chamber Connectivity)'), ('8_chamber', 'Yes (8 Chamber Connectivity)'), ('na', 'NA'), ('other', 'Any Other')], help_text='Hooter System', max_length=50)),
                ('castor_wheels', models.BooleanField(default=False, help_text='Castor Wheels')),
                ('pipe_length', models.CharField(blank=True, help_text='Pipe Length (Meter/NA)', max_length=50)),
                ('packaging', models.CharField(choices=[('normal', 'Normal'), ('wooden', 'Wooden'), ('other', 'Any other')], help_text='Packaging Options', max_length=50)),
                ('fat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('depends', 'Depends')], help_text='FAT', max_length=20)),
                ('refrigeration_system', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], help_text='Refrigeration System', max_length=20)),
                ('sg_system', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], help_text='S.G. System', max_length=20)),
                ('sensor', models.CharField(choices=[('yes', 'Yes'), ('na', 'NA')], help_text='Sensor', max_length=20)),
                ('tray_qty', models.CharField(help_text='Tray Qty. (Nos)', max_length=50)),
                ('tray_type', models.CharField(default='Perforated', help_text='Tray Type', max_length=100)),
                ('tray_moc', models.CharField(help_text='Tray MOC', max_length=100)),
                ('tray_dimension', models.CharField(help_text='Tray Dimension (W x D x H in MM)', max_length=100)),
                ('rack_qty', models.CharField(help_text='Rack Qty. (Nos/NA)', max_length=50)),
                ('protocol_documents', models.BooleanField(default=True, help_text='Protocol for DQ, IQ, and OQ, PQ Documents will be provided')),
                ('calibration_duration', models.CharField(default='1 hour', help_text='Calibration duration', max_length=50)),
                ('validation_duration', models.CharField(help_text='Validation duration (24/48/72 hours with load and 24/48/72 hours without load)', max_length=100)),
                ('validation_compressor', models.CharField(help_text='Validation at one set point with one compressor', max_length=100)),
                ('extra_validation_charge', models.BooleanField(default=True, help_text='Any extra Validation would be charged extra per day')),
                ('calibration_probes', models.CharField(help_text='Calibration and Validation with probes (8/9/10/Option)', max_length=100)),
                ('plc_validation', models.BooleanField(default=True, help_text='PLC Based System validation will be carried out')),
                ('training_handover', models.BooleanField(default=True, help_text='Training and handover of documents')),
                ('special_instructions', models.TextField(blank=True, help_text='Special Instructions')),
                ('advance_percentage', models.DecimalField(decimal_places=2, help_text='Advance Percentage', max_digits=5)),
                ('against_pi_percentage', models.DecimalField(decimal_places=2, help_text='Against PI Percentage', max_digits=5)),
                ('after_material_percentage', models.DecimalField(decimal_places=2, help_text='After receiving material at site Percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order Format',
                'verbose_name_plural': 'Work Order Formats',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
