# Generated by Django 4.2.7 on 2025-12-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0017_add_hrms_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='approved_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='approved_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='annualexhibitionbudget',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='approved_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='approved_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='callingdetails',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='callingdetails',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='callingdetails',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='callingdetails',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='dispatchchecklist',
            name='completed_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='dispatchchecklist',
            name='completed_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchchecklist',
            name='completed_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='dispatchchecklist',
            name='completed_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='dsr',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='dsr',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='dsr',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='dsr',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='gadrawing',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='gadrawing',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='gadrawing',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='gadrawing',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='hotorders',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='hotorders',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='hotorders',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='hotorders',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='performed_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='performed_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='performed_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='performed_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='mispurchaseorder',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='mispurchaseorder',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='mispurchaseorder',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='mispurchaseorder',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='newdata',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='newdata',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='newdata',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='newdata',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='newdatadetails',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='newdatadetails',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='newdatadetails',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='newdatadetails',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='odplan',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='odplan',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='odplan',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='odplan',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='odplanremarks',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='odplanremarks',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='odplanremarks',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='odplanremarks',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='odplanvisitreport',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='odplanvisitreport',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='odplanvisitreport',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='odplanvisitreport',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='orderexpectednextmonth',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='orderexpectednextmonth',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='orderexpectednextmonth',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='orderexpectednextmonth',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='orderloss',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='orderloss',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='orderloss',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='orderloss',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='packingdetails',
            name='packed_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='packingdetails',
            name='packed_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='packingdetails',
            name='packed_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='packingdetails',
            name='packed_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='pendingpayment2024',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='pendingpayment2024',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='pendingpayment2024',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='pendingpayment2024',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='pendingpayment2025',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='pendingpayment2025',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='pendingpayment2025',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='pendingpayment2025',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='podetails',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='podetails',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='podetails',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='podetails',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='postatus',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='postatus',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='postatus',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='postatus',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='assigned_to_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='assigned_to_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='assigned_to_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='assigned_to_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='projecttoday',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='projecttoday',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='projecttoday',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='projecttoday',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='qctracking',
            name='inspector_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='qctracking',
            name='inspector_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='qctracking',
            name='inspector_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='qctracking',
            name='inspector_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='region',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='region',
            name='manager_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='manager_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='manager_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='technicaldiscussion',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='technicaldiscussion',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='technicaldiscussion',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='technicaldiscussion',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='urs',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='urs',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='urs',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='urs',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='visitparticipant',
            name='participant_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='visitparticipant',
            name='participant_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='visitparticipant',
            name='participant_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='visitparticipant',
            name='participant_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='workorder',
            name='allocated_to_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='workorder',
            name='allocated_to_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='allocated_to_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='allocated_to_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='workorderformat',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='workorderformat',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='workorderformat',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='workorderformat',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AlterField(
            model_name='annualexhibitionbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callingdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followupstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gadrawing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotorders',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquirylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mispurchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newdatadetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odplanremarks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odplanvisitreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderexpectednextmonth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderloss',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingpayment2024',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingpayment2025',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttoday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicaldiscussion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklysummary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderformat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
