# Generated by Django 4.2.7 on 2026-01-17 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_app', '0018_add_all_hrms_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='HRMS User Email', max_length=254),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by_full_name',
            field=models.CharField(blank=True, help_text='HRMS User Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='HRMS User ID', null=True),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by_username',
            field=models.CharField(blank=True, help_text='HRMS Username', max_length=150),
        ),
        migrations.AlterField(
            model_name='quotationrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
